[package]
name = "shared"
version = "0.0.0"
edition = "2024"

[dependencies]
burn = { workspace = true }
image = { version = "0.25.5", optional = true }


[features]
default = []
train = ["burn/train", "dep:image"]
